name: CPanel Deployment
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🎉 Auto Deploy Server
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        protocol: ftps
        port: ${{ secrets.FTP_PORT }}
        local-dir: dist/
        exclude: .git*
          - .git*/**
          - .github
